cp land/018.png land/北の不死院.png
cp land/000.png land/火継ぎの祭祀場.png
cp land/035.png land/城下不死街.png
cp land/039.png land/城下不死教区.png
cp land/011.png land/狭間の森.png
cp land/032.png land/飛竜の谷.png
cp land/036.png land/小ロンド遺跡.png
cp land/038.png land/深淵.png
cp land/005.png land/黒い森の庭.png
cp land/037.png land/不死街下層.png
cp land/040.png land/最下層.png
cp land/022.png land/病み村.png
cp land/020.png land/クラーグの住処.png
cp land/031.png land/デーモン遺跡.png
cp land/024.png land/混沌の廃墟イザリス.png
cp land/002.png land/センの古城.png
cp land/004.png land/アノールロンド.png
cp land/033.png land/公爵の書庫.png
cp land/033.png land/結晶洞窟.png
cp land/034.png land/エレーミアス絵画世界.png
cp land/014.png land/ウーラシールの霊廟.png
cp land/014.png land/王家の裏庭.png
cp land/007.png land/ウーラシール市街.png
cp land/023.png land/深淵の穴.png
cp land/000.png land/地下墓地.png
cp land/026.png land/巨人墓場.png
cp land/008.png land/大樹のうつろ.png
cp land/006.png land/灰の湖.png
